repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black .
        language: system
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort .
        language: system
        pass_filenames: false

      - id: flake8
        name: Flake8
        entry: flake8 .
        language: system
        pass_filenames: false